FROM python:3.9

# Crear usuario seguro
RUN useradd -m -u 1000 user
USER user
ENV PATH="/home/user/.local/bin:$PATH"

WORKDIR /app

# Instalar dependencias
COPY --chown=user requirements.txt requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copiar el resto del código
COPY --chown=user . /app

# Ejecutar FastAPI desde app.py
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]