FROM python:3.11-slim

WORKDIR /app

# Copiar todo el contenido de deployment/
COPY . .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Ejecutar FastAPI desde api.py
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "7860"]